engines:
  eslint:
      enabled: true

ratings:
  paths:
  - "Frontend-Ng1/www/app/**"

exclude_paths:
- "Backend/**/*"
- "Frontend-Ng1/gulp/**/*"
- "Frontend-Ng1/*.js"
- "Frontend-Ng1/*.json"
- "Frontend-Ng1/*.xml"
- "*.md"
- "*.xml"
- "LICENSE"